<package format="2">
  <name>interactive_marker_wrench_server</name>
  <version>2.1.2</version>
  <description>Interactive control for generic Wrench-based robots using interactive markers</description>
  <!--Maintainer of the original package-->
<!--  <maintainer email="mpurvis@clearpathrobotics.com">Mike Purvis</maintainer> -->
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>interactive_markers</depend>
  <depend>rclcpp</depend>
  <depend>tf2</depend>
  <depend>visualization_msgs</depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
