wrench_server_node:
  ros__parameters:
    use_stamped_msg: false
    topic: /test/gazebo_ros_force
    linear_scale:
      x: 1.0
      y: 1.0
      z: 1.0
    max_positive_linear_force:
      x: 1.0
      y: 1.0
      z: 1.0
    max_negative_linear_force:
      x: -1.0
      y: -1.0
      z: -1.0
